language: java
sudo: false
dist: xenial
group: edge

branches:
  only:
    # release tags
    - /^trellis-extensions-\d+\.\d+\.\d+$/

jobs:
  allow_failures:
      - env: JOB=aws

  include:
    - name: "Publish JavaDocs"
      stage: deploy
      jdk: openjdk11
      env: JOB=aws
      script: ./gradlew apidocs
      deploy:
          provider: s3
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_SECRET_KEY
          bucket: $AWS_BUCKET
          skip_cleanup: true
          local_dir: docs/apidocs/$(./gradlew -q getVersion)
          upload-dir: docs/trellis-extensions/$(./gradlew -q getVersion)/apidocs
          default_text_charset: 'utf-8'
          on:
              all_branches: true

