name: GitHub CD

on:
  push:
    tags:
      - trellis-extensions-[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]

    name: Java ${{ matrix.java }} environment

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: trellis
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2.1.0
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1.3.0
      with:
        java-version: ${{ matrix.java }}

    - name: Build with Gradle
      run: ./gradlew check assemble javadoc -x pmdMain
      env:
        QUARKUS_EXTERNAL_PGSQL: true
        QUARKUS_DATASOURCE_USERNAME: postgres
        QUARKUS_DATASOURCE_PASSWORD: postgres

  docker:
    needs: [build]
    runs-on: ubuntu-latest

    name: Deploy docker container
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Set up JDK 8
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 8

    - name: Publish Docker Container
      run: |
        docker login docker.pkg.github.com -u $GITHUB_ACTOR -p "${{ secrets.GITHUB_TOKEN }}"
        ./buildtools/src/main/resources/docker/publishToGitHub.sh

