name: GitHub CD

on:
  push:
    tags:
      - trellis-extensions-[0-9]+.[0-9]+.[0-9]+

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

  build:
    runs-on: ubuntu-latest
    needs: [validation]
    strategy:
      matrix:
        java: [11]

    name: Java ${{ matrix.java }} environment

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Build with Gradle
      run: ./gradlew check assemble javadoc -x pmdMain

  docker:
    needs: [build]
    runs-on: ubuntu-latest

    name: Deploy docker container
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Publish Docker Container
      run: |
        docker login docker.pkg.github.com -u $GITHUB_ACTOR -p "${{ secrets.GITHUB_TOKEN }}"
        ./buildtools/src/main/resources/docker/publishToGitHub.sh

  javadocs:
    name: Deploy javadocs to AWS
    needs: [build]
    runs-on: ubuntu-latest
    if: contains(github.ref, 'trellis-extensions')

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build API documentation
      run: |
          ./gradlew apidocs
          mkdir -p docs/trellis/$(./gradlew -q getVersion)
          mv docs/apidocs/$(./gradlew -q getVersion) docs/trellis-extensions/$(./gradlew -q getVersion)/apidocs

    - name: Sync to AWS S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read
      env:
          AWS_S3_BUCKET: ${{ secrets.AWS_DOCS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "docs/trellis-extensions"
          DEST_DIR: "docs/trellis-extensions"

