name: GitHub CI

on:
  push:
    branches:
      - master
      - trellis-[0-9]+.[0-9]+.x
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]

    name: Java ${{ matrix.java }} environment

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: trellis
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Cache
      uses: actions/cache@v1.1.0
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew check assemble javadoc -x pmdMain -x spotbugsMain || ./gradlew check assemble javadoc -x pmdMain -x spotbugsMain
      env:
        QUARKUS_EXTERNAL_PGSQL: true
        QUARKUS_DATASOURCE_USERNAME: postgres
        QUARKUS_DATASOURCE_PASSWORD: postgres

  security:
    runs-on: ubuntu-latest
    name: Security analysis

    steps:
    - uses: actions/checkout@v2
      #with:
        #path: trellis-extensions

    - name: Run Snyk to check for vulnerabilities
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        PROJECT_FOLDER: trellis-extensions
      run:
        docker run --name snyk -e SNYK_TOKEN -e PROJECT_FOLDER -v "/home/runner/work":"/project" snyk/snyk-cli:gradle-5.4 "monitor --all-sub-projects --org=trellisldp"

  postgres:
    runs-on: ubuntu-latest
    name: Java 8 (postgres) environment

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: trellis
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: "Java 8 (Quarkus Database)"
      run: ./gradlew check -p platform/quarkus -x pmdMain -x spotbugsMain install --scan
      env:
        QUARKUS_EXTERNAL_PGSQL: true
        QUARKUS_DATASOURCE_USERNAME: postgres
        QUARKUS_DATASOURCE_PASSWORD: postgres

  cassandra:
    runs-on: ubuntu-latest
    name: Java 8 (cassandra) environment

    services:
      cassandra:
        image: cassandra:3.11
        ports:
        - 9042:9042
        - 9160:9160
        options: --name cassandra -v /home/runner/work:/workspace

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: "Java 8 (Quarkus Cassandra)"
      run: |
          docker exec cassandra sh -c "/workspace/trellis-extensions/trellis-extensions/buildtools/src/main/resources/cassandra/initialize.sh /workspace/trellis-extensions/trellis-extensions/cassandra/src/main/resources"
          ./gradlew check -x :trellis-db:check -x :trellis-db-app:check -x pmdMain -x spotbugsMain install -Pcassandra --scan
      env:
          TEST_CASSANDRA: true

