name: Sonar Analysis

on:
  push:
    branches:
      - main
      - trellis-extensions-[0-9]+.[0-9]+.x
  pull_request:
    branches:
      - main

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

  sonar:
    needs: [validation]
    runs-on: ubuntu-latest
    name: Sonar analysis

    services:
      cassandra:
        image: cassandra:3.11
        ports:
        - 9042:9042
        - 9160:9160
        options: --name cassandra -v /home/runner/work:/workspace

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Initialize cassandra
      run: docker exec cassandra sh -c "/workspace/trellis-extensions/trellis-extensions/buildtools/src/main/resources/cassandra/initialize.sh /workspace/trellis-extensions/trellis-extensions/cassandra/src/main/resources"

    - name: Build with Gradle
      run: ./gradlew check assemble -x pmdMain jacocoRootReport sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=trellis-ldp
      env:
        TEST_CASSANDRA: true
        TEST_AWS: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_TEST_BUCKET: ${{ secrets.AWS_TEST_BUCKET }}
        AWS_TEST_TOPIC: ${{ secrets.AWS_TEST_TOPIC }}


